version: '3.8'

services:
  web:
    image: django-docker:0.0.1
    build: .
    command1: docker-compose exec web python manage.py flush --no-input
    command2: docker-compose exec web python manage.py migrate
    command3: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: