# Generated by Django 5.0 on 2023-12-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0006_alter_movie_age_limit_alter_profile_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('Kids', 'Kids'), ('All', 'All')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('single', 'Single')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('Kids', 'Kids'), ('All', 'All')], max_length=10),
        ),
    ]
